import Head from 'next/head'
import Script from 'next/script'
import Image from 'next/image'
import { useFetchUser } from '@/lib/authContext'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home(props) {


  return (
    <>
      <Head>
        <title>ZnProgs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.head}>


        <div className={styles.body}>
          <div className={styles.container}>
            <span className={styles.text}>Welcome to my blog website</span>
          </div>
          <br />
          <p>Blogs about coding Here, you'll find a collection of informative articles and tutorials to help you expand your knowledge in these exciting fields. Whether you're a seasoned developer or a beginner , you'll find valuable insights and tips to help you achieve your goals.So, join me on this journey of exploration and discovery as we dive deeper into the fascinating worlds of coding!</p>
          <button className={styles.blog_btn}><a href="/blogs" >Explore Blogs</a></button>
        </div>

      </main>
      <div className={styles.content}>
        <div className={styles.blogfeature}>

          <div className={styles.features}>
            <div >
              <img src="/coding.gif" className={styles.feimg} alt="" />
            </div>
            <div className={styles.list}>
              <h3>Blog Features</h3><br />
              <pre>
                <p>&rarr; Beginer friendly blogs no prerequisits required </p>
                <p>and starts from absolute begining</p><br />
                <p>&rarr; Easy to understand explained to the point </p>
                <p>and concise blogs for everyone to follow up</p><br />
                <p>&rarr; Consistant learning </p>
              </pre>
            </div>
          </div>
        </div>
        <div className={styles.headding}> <h3>Latest Blogs</h3></div>
        <div className={styles.blogs}>

          <section className="text-gray-400 bg-gray-900 body-font">
            <div className="container px-5 py-10 mx-auto">
              <div className="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-800 sm:flex-row flex-col">
                <div className="sm:w-32 sm:h-20 h-20 w-30 sm:mr-10 inline-flex items-center justify-center rounded-2xl text-indigo-400 bg-gray-800 flex-shrink-0">

                  <img className='rounded-2xl h-20' src={props.Tblogs?.data[0]?.attributes.CoverImg.data ? `${props.Tblogs.data[0].attributes.CoverImg.data.attributes.url}` : "https://dummyimage.com/720x600"} alt="" />
                </div>
                <div className="flex-grow sm:text-left text-center mt-6 sm:mt-0">
                  <h2 className="text-white text-lg title-font font-medium mb-2">{props.Tblogs?.data[0]?.attributes.Title}</h2>
                  <p className="leading-relaxed text-base">{props.Tblogs?.data[0]?.attributes.Description}</p>
                  <a className="mt-3 text-indigo-400 inline-flex items-center" href={'/blogpost/' + props.Tblogs?.data[0].attributes.slug}>Learn More &#8674;
                  </a>
                </div>
              </div>
              <div className="flex items-center lg:w-3/5 mx-auto border-b pb-10 mb-10 border-gray-800 sm:flex-row flex-col">
                <div className="flex-grow sm:text-left text-center mt-6 sm:mt-0">
                  <h2 className="text-white text-lg title-font font-medium mb-2">{props.Tblogs.data[1].attributes.Title}</h2>
                  <p className="leading-relaxed text-base">{props.Tblogs.data[1].attributes.Description}</p>
                  <a className="mt-3 text-indigo-400 inline-flex items-center" href={'/blogpost/' + props.Tblogs.data[1].attributes.slug}>Learn More &#8674;
                  </a>
                </div>
                <div className="sm:w-32 order-first sm:order-none sm:h-20 h-20 w-30 sm:ml-10 inline-flex items-center justify-center rounded-2xl text-indigo-400 bg-gray-800 flex-shrink-0">
                  <img className='rounded-2xl h-20' src={props.Tblogs.data[1].attributes.CoverImg.data ? `${props.Tblogs.data[1].attributes.CoverImg.data.attributes.url}` : "https://dummyimage.com/720x600"} alt="" />

                </div>
              </div>
              <div className="flex items-center lg:w-3/5 mx-auto sm:flex-row flex-col">
                <div className="sm:w-32 sm:h-20 h-20 w-30 sm:mr-10 inline-flex items-center justify-center rounded-2xl text-indigo-400 bg-gray-800 flex-shrink-0">
                  <img className='rounded-2xl h-20' src={props.Tblogs.data[2].attributes.CoverImg.data ? `${props.Tblogs.data[2].attributes.CoverImg.data.attributes.url}` : "https://dummyimage.com/720x600"} alt="" />
                </div>
                <div className="flex-grow sm:text-left text-center mt-6 sm:mt-0">
                  <h2 className="text-white text-lg title-font font-medium mb-2">{props.Tblogs.data[2].attributes.Title}</h2>
                  <p className="leading-relaxed text-base">{props.Tblogs.data[2].attributes.Description}</p>
                  <a className="mt-3 text-indigo-400 inline-flex items-center" href={'/blogpost/' + props.Tblogs.data[2].attributes.slug}>Learn More &#8674;
                  </a>
                </div>
              </div>
            </div>
          </section>

        </div>
        <div className={styles.tecnology}>
          <div><p className={styles.techtxt}>Technologies covered</p></div>
          <div className={styles.techimg}>
            <img src="/mongo.png" alt="" />
            <img src="/node.png" alt="" />
            <img src="/sql.png" alt="" />
            <img src="/react.png" alt="" />
            <img className={styles.next} src="/next.png" alt="" />
            <img src="/js.png" alt="" />
            <img src="/html.png" alt="" />
            <img src="/css.png" alt="" />
          </div>

        </div>
        <div className={styles.inspiration}>
          <b>Inspiration</b>
          <div className={styles.inspi}>

            I've always been interested in technology and how it can solve real-world problems. But it wasn't until I stumbled upon the "CodeWithHarry" YouTube channel that I really started to take coding seriously. <br /> <br />

            Harry's engaging teaching style and passion for coding really inspired me to dive deeper into the world of programming. From there, I started learning more about different programming languages and technologies, and eventually launched my own blog to share what I've learned along the way. <br /><br />

            If you're just getting started with coding, I highly recommend checking out CodeWithHarry and seeing where it takes you! <br /> <br />
            <div className={styles.cwhlink}>
              <a href="https://www.youtube.com/@CodeWithHarry" target="_blank" ><img className={styles.cwh} src="/cwh.jpg" alt="CWH" /></a>
              <div className={styles.link}>
                <a target="_blank" href="https://www.youtube.com/@CodeWithHarry">CodeWithHarry</a>
              </div>
            </div>
          </div>
        </div>
        <footer className={styles.foot}>
          <div className={styles.copy}>
            <p>ZaheenProgs |</p>
            <div className={styles.copywr}>
              Copyright © 2022 zaheenprogs.com
            </div>

          </div>

          <div className={styles.socials}>
            <div className={styles.more}>
              <p>More About Us</p>
              <a href="/contact">Contact</a><br />
              <a href="/contact">About</a>
            </div>
            <div className={styles.media}>
              <p>Social Media Handlles</p>
              <a href=" https://twitter.com/TheMatrixT8888?t=5ma9RI_L_a7nnpNWvMBRRw&s=08" target="_blank" rel="noopener noreferrer"><img src="/twitter.png" alt="" /></a>
              <a href="https://www.linkedin.com/in/mohamed-zaheen-a9a169256" target="_blank" rel="noopener noreferrer"><img src="/linked.png" alt="" /></a>
              <a href="https://instagram.com/__zaheen_mohd?igshid=NzMyMjgxZWIzNw==" target="_blank" rel="noopener noreferrer"><img src="/insta.png" alt="" /></a>
            </div>
          </div>


        </footer>
      </div>

    </>
  )
}


export async function getStaticProps(context) {
  let a = await fetch(`${process.env.NEXT_PUBLIC_STRAPI_URL}/blogs?populate=*&sort=id:DESC&pagination[limit]=3`)
  let Tblogs = await a.json();
  return {
    props: { Tblogs },
  }
}